---
kind: pipeline
type: docker
name: default

volumes:
- name: cache
  host:
    path: /cache/magic-wall


steps:

- name: docker-build-django
  image: plugins/docker
  settings:
    registry: r.sacovo.ch
    repo: r.sacovo.ch/sacovo/magic-wall-backend
    tags: ${DRONE_COMMIT_SHA}
    auto_tag: true
    username:
      from_secret: portus_username
    password:
      from_secret: portus_token
    cache_from: r.sacovo.ch/sacovo/magic-wall-backend

- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ./app/node_modules
  volumes:
  - name: cache
    path: /cache

- name: build-angular
  image: node
  commands:
  - cd app/
  - npm install
  - npm run build app -- --prod
  depends_on:
  - restore-cache

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ./app/node_modules
  volumes:
  - name: cache
    path: /cache
  depends_on:
  - build-angular

- name: docker-build-app
  image: plugins/docker
  settings:
    registry: r.sacovo.ch
    repo: r.sacovo.ch/sacovo/magic-wall-frontend
    tags: ${DRONE_COMMIT_SHA}
    auto_tag: true
    username:
      from_secret: portus_username
    password:
      from_secret: portus_token
    context: app/
    dockerfile: app/Dockerfile
  depends_on:
  - build-angular

---
kind: signature
hmac: a767a3443e89797cdb63ce2458a21cac2067eabe71a9b655316595671f85e57a

...
