---
kind: pipeline
type: docker
name: default

volumes:
- name: cache
  host:
    path: /cache/magic-wall

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ./.pip-cache
      - ./app/node_modules
  volumes:
  - name: cache
    path: /cache

- name: docker-build-django
  image: plugins/docker
  environment:
    PIP_CACHE_DIR: ".pip-cache"
  settings:
    registry: r.sacovo.ch
    repo: r.sacovo.ch/sacovo/magic-wall-backend
    tags: ${DRONE_COMMIT_SHA}
    auto_tag: true
    username:
      from_secret: portus_username
    password:
      from_secret: portus_token
    cache_from: r.sacovo.ch/sacovo/magic-wall-backend
    build_args_from_env:
    - PIP_CACHE_DIR
  depends_on:
  - restore-cache

- name: build-angular
  image: node
  commands:
  - cd app/
  - npm install
  - npm run build app -- --prod
  depends_on:
  - restore-cache

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ./app/node_modules
      - ./.pip
      - ./.pip-cache
  volumes:
  - name: cache
    path: /cache
  depends_on:
  - build-angular
  - docker-build-django

- name: docker-build-app
  image: plugins/docker
  settings:
    registry: r.sacovo.ch
    repo: r.sacovo.ch/sacovo/magic-wall-frontend
    tags: ${DRONE_COMMIT_SHA}
    auto_tag: true
    username:
      from_secret: portus_username
    password:
      from_secret: portus_token
    context: app/
    dockerfile: app/Dockerfile

  depends_on:
  - build-angular

---
kind: signature
hmac: f09d1b57e2f8f9c6c5be112570abaf65da7323bcf6e7abff8780422ab75dee9f

...
