---
kind: pipeline
type: docker
name: default

steps:
- name: docker-build-django
  image: plugins/docker
  settings:
    registry: r.sacovo.ch
    repo: r.sacovo.ch/sacovo/magic-wall-backend
    tags: ${DRONE_COMMIT_SHA}
    auto_tag: true
    username:
      from_secret: portus_username
    password:
      from_secret: portus_token

- name: restore-npm-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ./node_modules
  volumes:
  - name: cache
    path: /cache

- name: build-angular
  image: node
  commands:
  - cd app/
  - npm install
  - npm run build app -- --prod

- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ./node_modules
  volumes:
  - name: cache
    path: /cache


- name: docker-build-app
  image: plugins/docker
  settings:
    registry: r.sacovo.ch
    repo: r.sacovo.ch/sacovo/magic-wall-frontend
    tags: ${DRONE_COMMIT_SHA}
    auto_tag: true
    username:
      from_secret: portus_username
    password:
      from_secret: portus_token
    context: app/
    dockerfile: app/Dockerfile

  depends_on:
  - build-angular

volumes:
- name: cache
  host:
    path: /cache/magic-wall
---
kind: signature
hmac: 5cfb80d9074b64560e651b90779f5addee95bafda42b7259b8c01d990e7545bc

...
