# Generated by Django 3.1.4 on 2020-12-18 09:10

from django.db import migrations, models
import predict.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LatestResult',
            fields=[
                ('id',
                 models.BigAutoField(primary_key=True, serialize=False,
                                     verbose_name='id')),
                ('yes_percent',
                 models.FloatField(default=predict.models.nan,
                                   verbose_name='yes percent')),
                ('participation',
                 models.FloatField(default=predict.models.nan,
                                   verbose_name='participation')),
                ('yes_absolute',
                 models.IntegerField(default=-1, verbose_name='yes absolute')),
                ('no_absolute', models.IntegerField(default=-1,
                                                    verbose_name='no absolute')),
                ('is_final', models.BooleanField(default=False, verbose_name='is final')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'latest result',
                'verbose_name_plural': 'latest results',
                'ordering': ['votation', 'gemeinde'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id',
                 models.BigAutoField(primary_key=True, serialize=False,
                                     verbose_name='id')),
                ('yes_percent',
                 models.FloatField(default=predict.models.nan,
                                   verbose_name='yes percent')),
                ('participation',
                 models.FloatField(default=predict.models.nan,
                                   verbose_name='participation')),
                ('yes_absolute',
                 models.IntegerField(default=-1, verbose_name='yes absolute')),
                ('no_absolute', models.IntegerField(default=-1,
                                                    verbose_name='no absolute')),
                ('is_final', models.BooleanField(default=False, verbose_name='is final')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
                'ordering': ['votation', 'gemeinde'],
            },
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('t',
                 models.DateTimeField(auto_now_add=True,
                                      primary_key=True,
                                      serialize=False)),
            ],
            options={
                'ordering': ['-t'],
            },
        ),
        migrations.CreateModel(
            name='VotingModel',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('yes_projection',
                 models.FileField(blank=True,
                                  null=True,
                                  upload_to='projections/',
                                  verbose_name='yes projection')),
                ('participation_projection',
                 models.FileField(blank=True,
                                  null=True,
                                  upload_to='projections/',
                                  verbose_name='participation projection')),
            ],
            options={
                'verbose_name': 'voting model',
                'verbose_name_plural': 'voting models',
            },
        ),
    ]
