# Generated by Django 3.1.4 on 2020-12-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("votes", "0001_initial"), ("geo", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="VotingModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projection",
                    models.FileField(blank=True, null=True, upload_to="projections/"),
                ),
                (
                    "model_votations",
                    models.ManyToManyField(blank=True, to="votes.Votation"),
                ),
                (
                    "votation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projection",
                        to="votes.votation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("yes_percent", models.FloatField()),
                ("participation", models.FloatField()),
                ("yes_absolute", models.IntegerField()),
                ("no_absolute", models.IntegerField()),
                ("is_final", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "gemeinde",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                      to="geo.gemeinde"),
                ),
                (
                    "votation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                      to="votes.votation"),
                ),
            ],
        ),
    ]
