# Generated by Django 3.1.4 on 2020-12-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20201218_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestresult',
            name='participation',
            field=models.FloatField(default=0, verbose_name='participation'),
        ),
        migrations.AlterField(
            model_name='latestresult',
            name='yes_percent',
            field=models.FloatField(default=0, verbose_name='yes percent'),
        ),
        migrations.AlterField(
            model_name='result',
            name='participation',
            field=models.FloatField(default=0, verbose_name='participation'),
        ),
        migrations.AlterField(
            model_name='result',
            name='yes_percent',
            field=models.FloatField(default=0, verbose_name='yes percent'),
        ),
    ]
