# Generated by Django 3.1.4 on 2020-12-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20201226_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestresult',
            name='no_absolute',
            field=models.IntegerField(default=0, verbose_name='no absolute'),
        ),
        migrations.AlterField(
            model_name='latestresult',
            name='yes_absolute',
            field=models.IntegerField(default=0, verbose_name='yes absolute'),
        ),
        migrations.AlterField(
            model_name='result',
            name='no_absolute',
            field=models.IntegerField(default=0, verbose_name='no absolute'),
        ),
        migrations.AlterField(
            model_name='result',
            name='yes_absolute',
            field=models.IntegerField(default=0, verbose_name='yes absolute'),
        ),
    ]
