# Generated by Django 3.1.4 on 2020-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0002_votationdate_is_finished"),
        ("geo", "0002_auto_20201215_1243"),
        ("predict", "0005_auto_20201212_2030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="latestresult",
            options={
                "ordering": ["votation", "gemeinde"],
                "verbose_name": "latest result",
                "verbose_name_plural": "latest results",
            },
        ),
        migrations.AlterModelOptions(
            name="result",
            options={
                "ordering": ["votation", "gemeinde"],
                "verbose_name": "result",
                "verbose_name_plural": "results",
            },
        ),
        migrations.AlterModelOptions(
            name="votingmodel",
            options={
                "verbose_name": "voting model",
                "verbose_name_plural": "voting models",
            },
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="gemeinde",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.gemeinde",
                verbose_name="commune",
            ),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="id",
            field=models.BigAutoField(primary_key=True,
                                      serialize=False,
                                      verbose_name="id"),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="is_final",
            field=models.BooleanField(default=False, verbose_name="is final"),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="no_absolute",
            field=models.IntegerField(default=-1, verbose_name="no absolute"),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="participation",
            field=models.FloatField(default=float("nan"), verbose_name="participation"),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="votation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="votes.votation",
                verbose_name="votation",
            ),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="yes_absolute",
            field=models.IntegerField(default=-1, verbose_name="yes absolute"),
        ),
        migrations.AlterField(
            model_name="latestresult",
            name="yes_percent",
            field=models.FloatField(default=float("nan"), verbose_name="yes percent"),
        ),
        migrations.AlterField(
            model_name="result",
            name="gemeinde",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.gemeinde",
                verbose_name="commune",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="id",
            field=models.BigAutoField(primary_key=True,
                                      serialize=False,
                                      verbose_name="id"),
        ),
        migrations.AlterField(
            model_name="result",
            name="is_final",
            field=models.BooleanField(default=False, verbose_name="is final"),
        ),
        migrations.AlterField(
            model_name="result",
            name="no_absolute",
            field=models.IntegerField(default=-1, verbose_name="no absolute"),
        ),
        migrations.AlterField(
            model_name="result",
            name="participation",
            field=models.FloatField(default=float("nan"), verbose_name="participation"),
        ),
        migrations.AlterField(
            model_name="result",
            name="votation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="votes.votation",
                verbose_name="votation",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="yes_absolute",
            field=models.IntegerField(default=-1, verbose_name="yes absolute"),
        ),
        migrations.AlterField(
            model_name="result",
            name="yes_percent",
            field=models.FloatField(default=float("nan"), verbose_name="yes percent"),
        ),
        migrations.AlterField(
            model_name="votingmodel",
            name="model_votations",
            field=models.ManyToManyField(
                blank=True,
                related_name="_votingmodel_model_votations_+",
                to="votes.Votation",
                verbose_name="model votations",
            ),
        ),
        migrations.AlterField(
            model_name="votingmodel",
            name="participation_projection",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projections/",
                verbose_name="participation projection",
            ),
        ),
        migrations.AlterField(
            model_name="votingmodel",
            name="votation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projection",
                to="votes.votation",
                verbose_name="votation",
            ),
        ),
        migrations.AlterField(
            model_name="votingmodel",
            name="yes_projection",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projections/",
                verbose_name="yes projection",
            ),
        ),
    ]
