# Generated by Django 3.1.4 on 2020-12-15 11:45

from django.db import migrations, models
import predict.models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_auto_20201215_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestresult',
            name='participation',
            field=models.FloatField(default=predict.models.nan,
                                    verbose_name='participation'),
        ),
        migrations.AlterField(
            model_name='latestresult',
            name='yes_percent',
            field=models.FloatField(default=predict.models.nan,
                                    verbose_name='yes percent'),
        ),
        migrations.AlterField(
            model_name='result',
            name='participation',
            field=models.FloatField(default=predict.models.nan,
                                    verbose_name='participation'),
        ),
        migrations.AlterField(
            model_name='result',
            name='yes_percent',
            field=models.FloatField(default=predict.models.nan,
                                    verbose_name='yes percent'),
        ),
    ]
