# Generated by Django 3.1.4 on 2020-12-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Votation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("is_finished", models.BooleanField(default=False)),
                ("needs_staende", models.BooleanField()),
                ("is_accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VotationDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("json_url", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="VotationTitle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=280)),
                (
                    "votation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                      to="votes.votation"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="votation",
            name="date",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to="votes.votationdate"),
        ),
        migrations.AddConstraint(
            model_name="votationtitle",
            constraint=models.UniqueConstraint(
                fields=("language_code", "votation"),
                name="unique_language_per_vocation",
            ),
        ),
    ]
