# Generated by Django 3.1.4 on 2020-12-18 09:10

import django.db.models.deletion
from django.db import migrations, models

import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_finished',
                 models.BooleanField(default=False, verbose_name='is finished')),
                ('needs_staende', models.BooleanField(verbose_name='needs staende')),
                ('is_accepted',
                 models.BooleanField(default=False, verbose_name='is accepted')),
            ],
            options={
                'verbose_name': 'votation',
                'verbose_name_plural': 'votations',
            },
        ),
        migrations.CreateModel(
            name='VotationDate',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('json_url', models.URLField(max_length=500, verbose_name='json url')),
                ('is_finished',
                 models.BooleanField(default=False, verbose_name='is finished')),
            ],
            options={
                'verbose_name': 'votating day',
                'verbose_name_plural': 'voting days',
            },
        ),
        migrations.CreateModel(
            name='VotationTitle',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('language_code',
                 models.CharField(max_length=2, verbose_name='language code')),
                ('title', models.CharField(max_length=280, verbose_name='title')),
                ('votation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='votes.votation',
                                   verbose_name='votation')),
            ],
            options={
                'verbose_name': 'votation title',
                'verbose_name_plural': 'votation titles',
            },
        ),
        migrations.AddField(
            model_name='votation',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='votes.votationdate',
                                    verbose_name='date'),
        ),
        migrations.AddField(
            model_name='votation',
            name='tags',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='votationtitle',
            constraint=models.UniqueConstraint(fields=('language_code', 'votation'),
                                               name='unique_language_per_vocation'),
        ),
    ]
