# Generated by Django 3.1.4 on 2020-12-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votationtitle',
            name='votation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='titles',
                                    to='votes.votation',
                                    verbose_name='votation'),
        ),
    ]
