# Generated by Django 3.1.4 on 2020-12-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20201218_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votationdate',
            options={
                'ordering': ['-start_date'],
                'verbose_name': 'votating day',
                'verbose_name_plural': 'voting days'
            },
        ),
    ]
