# Generated by Django 3.1.4 on 2020-12-27 15:46

from django.db import migrations, models

import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('votes', '0003_auto_20201223_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votation',
            options={
                'ordering': ['-date__start_date'],
                'verbose_name': 'votation',
                'verbose_name_plural': 'votations'
            },
        ),
        migrations.AddField(
            model_name='votationdate',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='is demo'),
        ),
        migrations.AlterField(
            model_name='votation',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
