# Generated by Django 3.1.4 on 2020-12-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20201227_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='votationdate',
            name='latest_hash',
            field=models.CharField(blank=True, max_length=500,
                                   verbose_name='latest hash'),
        ),
    ]
