# Generated by Django 3.1.4 on 2021-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_votation_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votationtitle',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
