FROM node:lts AS app
RUN npm install -g @angular/cli
WORKDIR /app

COPY package.json /app/
RUN npm install 

COPY ./ /app/

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "50", "--disable-host-check"]
