# Generated by Django 3.1.4 on 2020-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("geo", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="gemeinde",
            options={
                "verbose_name": "commune",
                "verbose_name_plural": "communes"
            },
        ),
        migrations.AlterModelOptions(
            name="kanton",
            options={
                "verbose_name": "canton",
                "verbose_name_plural": "cantons"
            },
        ),
        migrations.AlterField(
            model_name="gemeinde",
            name="kanton",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.kanton",
                verbose_name="canton",
            ),
        ),
        migrations.AlterField(
            model_name="gemeinde",
            name="voters",
            field=models.IntegerField(verbose_name="eligible voters"),
        ),
        migrations.AlterField(
            model_name="kanton",
            name="standesstimme",
            field=models.FloatField(default=1.0, verbose_name="standesstimme"),
        ),
    ]
